import { NetworkConfig } from './types';

// Type for Vite environment variables
interface ViteEnv {
  VITE_AZTEC_NODE_URL?: string;
  VITE_DRIPPER_CONTRACT_ADDRESS?: string;
  VITE_TOKEN_CONTRACT_ADDRESS?: string;
  VITE_DEPLOYER_ADDRESS?: string;
  VITE_DRIPPER_DEPLOYMENT_SALT?: string;
  VITE_TOKEN_DEPLOYMENT_SALT?: string;
  VITE_PROVER_ENABLED?: string;
}

// Access Vite env vars (populated from .env file by Vite)
const env = (import.meta as unknown as { env: ViteEnv }).env;

/**
 * Validates that required environment variables are set.
 * These are generated by running `yarn deploy-contracts`.
 */
const getRequiredEnv = (key: keyof ViteEnv, friendlyName: string): string => {
  const value = env[key];
  if (!value) {
    throw new Error(
      `Missing required environment variable: ${key}\n\n` +
      `Please run 'yarn deploy-contracts' first to deploy contracts and generate the .env file.\n` +
      `Make sure the Aztec sandbox is running before deploying.`
    );
  }
  return value;
};

/**
 * Sandbox configuration for local development.
 * 
 * IMPORTANT: Run `yarn deploy-contracts` first to generate the .env file
 * with contract addresses. The sandbox must be running before deploying.
 */
export const SANDBOX_CONFIG: NetworkConfig = {
  name: 'sandbox',
  displayName: 'Local Sandbox',
  description: 'Local development environment with deterministic addresses',
  nodeUrl: env.VITE_AZTEC_NODE_URL || 'http://localhost:8080',
  dripperContractAddress: getRequiredEnv('VITE_DRIPPER_CONTRACT_ADDRESS', 'Dripper Contract Address'),
  tokenContractAddress: getRequiredEnv('VITE_TOKEN_CONTRACT_ADDRESS', 'Token Contract Address'),
  deployerAddress: getRequiredEnv('VITE_DEPLOYER_ADDRESS', 'Deployer Address'),
  dripperDeploymentSalt: getRequiredEnv('VITE_DRIPPER_DEPLOYMENT_SALT', 'Dripper Deployment Salt'),
  tokenDeploymentSalt: getRequiredEnv('VITE_TOKEN_DEPLOYMENT_SALT', 'Token Deployment Salt'),
  proverEnabled: env.VITE_PROVER_ENABLED !== 'false',
  isTestnet: false,
};
