
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import TestLogicContractArtifactJson from '../target/test_logic_contract-TestLogic.json' with { type: 'json' };
export const TestLogicContractArtifact = loadContractArtifact(TestLogicContractArtifactJson as NoirCompiledContract);


      export type EscrowDetailsLogContent = {
        escrow: AztecAddressLike
master_secret_keys: { nsk_m: FieldLike, ivsk_m: FieldLike, ovsk_m: FieldLike, tsk_m: FieldLike }
      }
    

/**
 * Type-safe interface for contract TestLogic;
 */
export class TestLogicContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, TestLogicContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): TestLogicContract {
    return Contract.at(address, TestLogicContract.artifact, wallet) as TestLogicContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, escrow_class_id: FieldLike) {
    return new DeployMethod<TestLogicContract>(PublicKeys.default(), wallet, TestLogicContractArtifact, (instance, wallet) => TestLogicContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, escrow_class_id: FieldLike) {
    return new DeployMethod<TestLogicContract>(publicKeys, wallet, TestLogicContractArtifact, (instance, wallet) => TestLogicContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof TestLogicContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<TestLogicContract['methods'][M]>
  ) {
    return new DeployMethod<TestLogicContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      TestLogicContractArtifact,
      (instance, wallet) => TestLogicContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return TestLogicContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(TestLogicContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'escrow_class_id'> {
      return {
        escrow_class_id: {
      slot: new Fr(1n),
    }
      } as ContractStorageLayout<'escrow_class_id'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(escrow_class_id: field) */
    constructor: ((escrow_class_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_escrow(master_secret_keys: struct) */
    get_escrow: ((master_secret_keys: { nsk_m: FieldLike, ivsk_m: FieldLike, ovsk_m: FieldLike, tsk_m: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** secret_keys_to_public_keys(master_secret_keys: struct) */
    secret_keys_to_public_keys: ((master_secret_keys: { nsk_m: FieldLike, ivsk_m: FieldLike, ovsk_m: FieldLike, tsk_m: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** share_escrow(account: struct, escrow: struct, master_secret_keys: struct) */
    share_escrow: ((account: AztecAddressLike, escrow: AztecAddressLike, master_secret_keys: { nsk_m: FieldLike, ivsk_m: FieldLike, ovsk_m: FieldLike, tsk_m: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw(escrow: struct, account: struct, token: struct, amount: integer) */
    withdraw: ((escrow: AztecAddressLike, account: AztecAddressLike, token: AztecAddressLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** withdraw_nft(escrow: struct, account: struct, nft: struct, token_id: field) */
    withdraw_nft: ((escrow: AztecAddressLike, account: AztecAddressLike, nft: AztecAddressLike, token_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { EscrowDetailsLogContent: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      EscrowDetailsLogContent: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "escrow",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "aztec::protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "master_secret_keys",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "nsk_m",
                        "type": {
                            "kind": "field"
                        }
                    },
                    {
                        "name": "ivsk_m",
                        "type": {
                            "kind": "field"
                        }
                    },
                    {
                        "name": "ovsk_m",
                        "type": {
                            "kind": "field"
                        }
                    },
                    {
                        "name": "tsk_m",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "escrow_contract::types::escrow_details_event::MasterSecretKeys"
            }
        }
    ],
    "path": "TestLogic::EscrowDetailsLogContent"
},
        eventSelector: EventSelector.fromString("0xf38cfc93"),
        fieldNames: ["escrow","master_secret_keys"],
      }
    };
  }
  
}
