/* Autogenerated file, do not edit! */
import { loadContractArtifact, loadContractArtifactForPublic } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, DeployMethod } from '@aztec/aztec.js/contracts';
import { Fr } from '@aztec/aztec.js/fields';
import { PublicKeys } from '@aztec/aztec.js/keys';
import TokenContractArtifactJson from '../target/token_contract-Token.json' with { type: 'json' };
export const TokenContractArtifact = loadContractArtifact(TokenContractArtifactJson);
/**
 * Type-safe interface for contract Token;
 */
export class TokenContract extends ContractBase {
    constructor(address, wallet) {
        super(address, TokenContractArtifact, wallet);
    }
    /**
     * Creates a contract instance.
     * @param address - The deployed contract's address.
     * @param wallet - The wallet to use when interacting with the contract.
     * @returns A new Contract instance.
     */
    static at(address, wallet) {
        return Contract.at(address, TokenContract.artifact, wallet);
    }
    /**
     * Creates a tx to deploy a new instance of this contract.
     */
    static deploy(wallet, name, symbol, decimals, asset, upgrade_authority) {
        return new DeployMethod(PublicKeys.default(), wallet, TokenContractArtifact, (instance, wallet) => TokenContract.at(instance.address, wallet), Array.from(arguments).slice(1));
    }
    /**
     * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
     */
    static deployWithPublicKeys(publicKeys, wallet, name, symbol, decimals, asset, upgrade_authority) {
        return new DeployMethod(publicKeys, wallet, TokenContractArtifact, (instance, wallet) => TokenContract.at(instance.address, wallet), Array.from(arguments).slice(2));
    }
    /**
     * Creates a tx to deploy a new instance of this contract using the specified constructor method.
     */
    static deployWithOpts(opts, ...args) {
        return new DeployMethod(opts.publicKeys ?? PublicKeys.default(), opts.wallet, TokenContractArtifact, (instance, wallet) => TokenContract.at(instance.address, wallet), Array.from(arguments).slice(1), opts.method ?? 'constructor');
    }
    /**
     * Returns this contract's artifact.
     */
    static get artifact() {
        return TokenContractArtifact;
    }
    /**
     * Returns this contract's artifact with public bytecode.
     */
    static get artifactForPublic() {
        return loadContractArtifactForPublic(TokenContractArtifactJson);
    }
    static get storage() {
        return {
            name: {
                slot: new Fr(1n),
            },
            symbol: {
                slot: new Fr(3n),
            },
            decimals: {
                slot: new Fr(5n),
            },
            private_balances: {
                slot: new Fr(7n),
            },
            total_supply: {
                slot: new Fr(8n),
            },
            public_balances: {
                slot: new Fr(9n),
            },
            minter: {
                slot: new Fr(10n),
            },
            upgrade_authority: {
                slot: new Fr(12n),
            },
            asset: {
                slot: new Fr(14n),
            }
        };
    }
}
