import type { ContractArtifact } from '@aztec/aztec.js/abi';
import type { ContractBase } from '@aztec/aztec.js/contracts';
import type { ContractFunctionInteraction } from '@aztec/aztec.js/contracts';
import type { UseMutationResult } from '@tanstack/react-query';

/**
 * Extract method names from a contract class.
 * Works with autogenerated Aztec contract classes.
 *
 * @example
 * type DripperMethods = MethodsOf<DripperContract>;
 * // = 'drip_to_private' | 'drip_to_public' | ...
 */
export type MethodsOf<TContract> = TContract extends { methods: infer M }
  ? keyof M
  : never;

/**
 * Extract the argument types for a specific method of a contract.
 *
 * @example
 * type Args = ArgsOf<DripperContract, 'drip_to_private'>;
 * // = [AztecAddressLike, bigint | number]
 */
export type ArgsOf<
  TContract,
  TMethod extends MethodsOf<TContract>,
> = TContract extends {
  methods: {
    [K in TMethod]: (...args: infer A) => ContractFunctionInteraction;
  };
}
  ? A
  : never;

/**
 * Type helper to extract contract type from a contract class.
 * Uses the static `at` method signature to infer the contract instance type.
 *
 * The `at` parameter uses `never[]` intentionally — this type is only used for
 * artifact access and contract type inference, never for calling `at` directly.
 * Using `never[]` avoids coupling to a specific `at` method signature, which
 * varies across Aztec.js versions (sync vs async, different parameter sets).
 */
export type ContractClassFor<TContract extends ContractBase> = {
  artifact: ContractArtifact;
  at: (...args: never[]) => Promise<TContract> | TContract;
};

// =============================================================================
// Scope key type
// =============================================================================

/** Key-scoping input for use-aztec read hooks (wagmi-style `scopeKey`). */
export type ScopeKey = string | readonly unknown[];

// =============================================================================
// Shared TanStack Query/Mutation option types
// =============================================================================

/** TanStack Query options passthrough for read hooks. */
export interface ContractQueryOptions<TSelectData = unknown> {
  /** Additional gate to enable/disable the query (default: true) */
  enabled?: boolean;
  /** Time in ms before data is considered stale */
  staleTime?: number;
  /** Time in ms before inactive query data is garbage collected */
  gcTime?: number;
  /** Polling interval in ms, or false to disable */
  refetchInterval?: number | false;
  /** Whether to refetch on window focus */
  refetchOnWindowFocus?: boolean;
  /** Transform the raw result before returning */
  select?: (data: unknown) => TSelectData;
  /** Retry count or boolean */
  retry?: number | boolean;
}

// =============================================================================
// useReadContract types
// =============================================================================

/**
 * Parameters for the declarative useReadContract hook.
 * Mirrors wagmi's useReadContract API with Aztec-specific extensions.
 */
export interface UseReadContractParams<
  TContract extends ContractBase,
  TMethod extends MethodsOf<TContract>,
  TSelectData = unknown,
> {
  /** Contract class — used for type inference and artifact */
  contract: ContractClassFor<TContract>;
  /** Contract address. Set to undefined to auto-disable the query. */
  address: string | undefined;
  /** Method name to simulate */
  functionName: TMethod;
  /** Method arguments. Set to undefined to auto-disable the query. */
  args: ArgsOf<TContract, TMethod> | undefined;
  /** Wagmi-style scope key — used as a prefix for the auto-generated query key. */
  scopeKey?: ScopeKey;
  /** TanStack Query options (enabled, staleTime, gcTime, etc.) */
  query?: ContractQueryOptions<TSelectData>;
}

// =============================================================================
// useWriteContract types
// =============================================================================

/**
 * Data returned from a successful write operation.
 */
export interface WriteContractData {
  txHash?: string;
  result?: unknown;
}

/**
 * Per-call callback options for writeContract / writeContractAsync.
 * Mirrors wagmi's pattern of passing callbacks as a second argument.
 */
export interface WriteContractCallOptions {
  onSuccess?: (data: WriteContractData) => void;
  onError?: (error: Error) => void;
  onSettled?: (
    data: WriteContractData | undefined,
    error: Error | null
  ) => void;
}

/**
 * Parameters passed per-call to writeContract / writeContractAsync.
 * Fee payment method is typed as `unknown` to keep use-aztec agnostic —
 * the execution client is responsible for interpreting it.
 */
export interface WriteContractMutateParams<
  TContract extends ContractBase,
  TMethod extends MethodsOf<TContract>,
> {
  /** Contract class — used for type inference and artifact */
  contract: ContractClassFor<TContract>;
  /** Contract address */
  address: string;
  /** Method name to call */
  functionName: TMethod;
  /** Method arguments */
  args: ArgsOf<TContract, TMethod>;
  /** Optional fee payment policy consumed by the injected wallet adapter. */
  feePaymentMethod?: unknown;
  /** Timeout for transaction confirmation in seconds (default: 900) */
  timeout?: number;
  /** Receipt polling options for browser wallet */
  receiptPolling?: { intervalMs?: number; maxAttempts?: number };
}

/**
 * Options for the useWriteContract hook.
 * Mirrors wagmi v2: hook-level callbacks live under `mutation`.
 */
export interface UseWriteContractOptions {
  /** TanStack Mutation callbacks (onSuccess, onError, onSettled) */
  mutation?: WriteContractCallOptions;
}

/**
 * Generic `mutate` signature — infers `TContract` and `TMethod` from params
 * so that `args` is compile-time checked against the contract ABI.
 */
type UseWriteContractMutate = <
  TContract extends ContractBase,
  TMethod extends MethodsOf<TContract>,
>(
  params: WriteContractMutateParams<TContract, TMethod>,
  options?: WriteContractCallOptions
) => void;

/**
 * Generic `mutateAsync` signature — same inference, returns a Promise.
 */
type UseWriteContractMutateAsync = <
  TContract extends ContractBase,
  TMethod extends MethodsOf<TContract>,
>(
  params: WriteContractMutateParams<TContract, TMethod>,
  options?: WriteContractCallOptions
) => Promise<WriteContractData>;

/**
 * Return type for the useWriteContract hook.
 * Overrides `mutate` / `mutateAsync` with generic signatures so callers
 * get compile-time arg checking without needing explicit type annotations.
 */
export type UseWriteContractReturn = Omit<
  UseMutationResult<WriteContractData, Error, WriteContractActionParams>,
  'mutate' | 'mutateAsync'
> & {
  mutate: UseWriteContractMutate;
  mutateAsync: UseWriteContractMutateAsync;
};

// =============================================================================
// useReadContracts types (batch reads)
// =============================================================================

/** A single contract read config within a batch (one entry in the contracts array). */
export interface ReadContractsContract<
  TContract extends ContractBase = ContractBase,
  TMethod extends MethodsOf<TContract> = MethodsOf<TContract>,
> {
  contract: ContractClassFor<TContract>;
  address: string;
  functionName: TMethod;
  args: ArgsOf<TContract, TMethod>;
}

/** Per-result shape when allowFailure is true. Discriminated union on `status`. */
export type ReadContractResult =
  | { status: 'success'; result: unknown; error?: undefined }
  | { status: 'failed'; result?: undefined; error: Error };

/** Params for useReadContracts. */
export interface UseReadContractsParams<
  TAllowFailure extends boolean = true,
  TSelectData = TAllowFailure extends true ? ReadContractResult[] : unknown[],
> {
  contracts: ReadContractsContract[];
  allowFailure?: TAllowFailure;
  /** Wagmi-style scope key — used as a prefix for the auto-generated query key. */
  scopeKey?: ScopeKey;
  /** TanStack Query options (enabled, staleTime, gcTime, etc.) */
  query?: ContractQueryOptions<TSelectData>;
}

// =============================================================================
// Action param types
// =============================================================================

/** Action params for writeContract. */
export interface WriteContractActionParams {
  contract: { artifact: ContractArtifact };
  address: string;
  functionName: string;
  args: unknown[];
  feePaymentMethod?: unknown;
  timeout?: number;
  receiptPolling?: { intervalMs?: number; maxAttempts?: number };
}

// =============================================================================
