import type { ContractFunctionInteraction } from '@aztec/aztec.js/contracts';

/**
 * Extract method names from a contract class.
 * Works with autogenerated Aztec contract classes.
 *
 * @example
 * type DripperMethods = MethodsOf<DripperContract>;
 * // = 'drip_to_private' | 'drip_to_public' | ...
 */
export type MethodsOf<TContract> = TContract extends { methods: infer M }
  ? keyof M
  : never;

/**
 * Extract the argument types for a specific method of a contract.
 *
 * @example
 * type Args = ArgsOf<DripperContract, 'drip_to_private'>;
 * // = [AztecAddressLike, bigint | number]
 */
export type ArgsOf<
  TContract,
  TMethod extends MethodsOf<TContract>,
> = TContract extends {
  methods: {
    [K in TMethod]: (...args: infer A) => ContractFunctionInteraction;
  };
}
  ? A
  : never;

/**
 * Configuration for a contract write operation.
 */
export interface WriteContractConfig<
  TContract,
  TMethod extends MethodsOf<TContract>,
> {
  address: string;
  functionName: TMethod;
  args: ArgsOf<TContract, TMethod>;
}

/**
 * Result of a contract write operation.
 */
export interface WriteContractResult {
  success: boolean;
  txHash?: string;
  error?: string;
  data?: unknown;
}

/**
 * Configuration for a contract read/simulate operation.
 */
export interface ReadContractConfig<
  TContract,
  TMethod extends MethodsOf<TContract>,
> {
  address: string;
  functionName: TMethod;
  args: ArgsOf<TContract, TMethod>;
}

/**
 * Result of a contract read operation.
 */
export interface ReadContractResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}
