import type { ContractArtifact } from '@aztec/aztec.js/abi';
import type { AztecAddress } from '@aztec/aztec.js/addresses';
import type {
  ContractFunctionInteraction,
  ContractBase,
} from '@aztec/aztec.js/contracts';
import type { Wallet } from '@aztec/aztec.js/wallet';

/**
 * Type helper to extract contract type from a contract class.
 * Matches the static interface of generated Aztec contract classes.
 */
export type ContractClassFor<TContract extends ContractBase> = {
  artifact: ContractArtifact;
  at: (address: AztecAddress, wallet: Wallet) => TContract;
};

/**
 * Extract method names from a contract class.
 * Works with autogenerated Aztec contract classes.
 *
 * @example
 * type DripperMethods = MethodsOf<DripperContract>;
 * // = 'drip_to_private' | 'drip_to_public' | ...
 */
export type MethodsOf<TContract> = TContract extends { methods: infer M }
  ? keyof M
  : never;

/**
 * Extract the argument types for a specific method of a contract.
 *
 * @example
 * type Args = ArgsOf<DripperContract, 'drip_to_private'>;
 * // = [AztecAddressLike, bigint | number]
 */
export type ArgsOf<
  TContract,
  TMethod extends MethodsOf<TContract>,
> = TContract extends {
  methods: {
    [K in TMethod]: (...args: infer A) => ContractFunctionInteraction;
  };
}
  ? A
  : never;

/**
 * Configuration for a contract write operation.
 */
export interface WriteContractConfig<
  TContract,
  TMethod extends MethodsOf<TContract>,
> {
  address: string;
  functionName: TMethod;
  args: ArgsOf<TContract, TMethod>;
}

/**
 * Result of a contract write operation.
 */
export interface WriteContractResult {
  success: boolean;
  txHash?: string;
  error?: string;
  data?: unknown;
}

/**
 * Configuration for a contract read/simulate operation.
 */
export interface ReadContractConfig<
  TContract,
  TMethod extends MethodsOf<TContract>,
> {
  address: string;
  functionName: TMethod;
  args: ArgsOf<TContract, TMethod>;
}

/**
 * Result of a contract read operation.
 */
export interface ReadContractResult<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
}

/**
 * Configuration for a dynamic (untyped) contract read/simulate operation.
 * Used when only a raw artifact is available (e.g. Contract Explorer).
 */
export interface DynamicReadContractConfig {
  artifact: ContractArtifact;
  address: string;
  functionName: string;
  args: unknown[];
}

/**
 * Configuration for a dynamic (untyped) contract write operation.
 * Used when only a raw artifact is available (e.g. Contract Explorer).
 */
export interface DynamicWriteContractConfig {
  artifact: ContractArtifact;
  address: string;
  functionName: string;
  args: unknown[];
}
