/**
 * Sandbox deployment data.
 *
 * AUTO-GENERATED by `yarn deploy-contracts` — do not edit manually.
 * Run `yarn deploy-contracts` to deploy contracts and regenerate the JSON.
 */

import sandboxJson from './sandbox.json';
import type { NetworkDeployments } from './types';

export const sandboxDeployments = {
  dripper: {
    address: sandboxJson.dripperContract.address,
    salt: sandboxJson.dripperContract.salt,
    deployer: sandboxJson.deployer,
  },
  token: {
    address: sandboxJson.tokenContract.address,
    salt: sandboxJson.tokenContract.salt,
    deployer: sandboxJson.deployer,
  },
} as const satisfies NetworkDeployments;
